include ../../ThirdParty/PSCommon/BuildSystem/CommonDefs.mak

BIN_DIR = ../../Bin

INC_DIRS = \
	../../Include \
	../Common\
	../../Samples/RGBSNReader_Linux

SRC_FILES = *.cpp

USED_LIBS += OpenNI2
# USED_LIBS+=../../Samples/SimpleRead/SonixCamera
USED_LIBS+=SonixCamera
USED_LIBS+=pthread


EXE_NAME = RGBSNReader

CFLAGS += -Wall
	

include ../../ThirdParty/PSCommon/BuildSystem/CommonCppMakefile
//cp:
	// cp libSonixCamera.a  ../../Bin/x64-Release	
